theme = "maupassant"
baseURL = "https://onyas.github.io/focusit"
languageCode = "zh-CN"
title = "Edward Zheng"

[author]
  name = "Edward"

[params]
  author = "Edward"
  subtitle = "Full-stack developer at work, full-time dad at home -- mastering the art of crash management in both."
  keywords = "golang,java,博客,团队管理,python,软件架构,大数据、敏捷、软件架构"
  description = "专注于IT互联网，包括但不限于Java、Go语言、Python、大数据、敏捷、软件架构等"
  busuanzi = true
  favicon = "favicon.ico"

[menu]

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4
  

[[params.links]]
  title = "onyas"
  name = "onyas"
  url = "https://github.com/onyas"

[params.utteranc]
    enable = true
    repo = "onyas/focusit"    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种


summaryLength = 70 

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true

## 是否禁止URL Path转小写
disablePathToLower = true

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  extensions = ["hardLineBreak"]